/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GestorArchivo;

import GestorArchivo.GestorArchivoBE;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class GestorArchivoFE extends javax.swing.JPanel {
    private GestorArchivoBE gestorArchivosBE;

    public GestorArchivoFE(GestorArchivoBE gestorArchivoBE) {
        this.gestorArchivosBE = gestorArchivoBE;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRutaYAbrir = new javax.swing.JButton();
        btnEscogerPath = new javax.swing.JButton();
        txtProcesamiento = new javax.swing.JLabel();
        valorProcesamiento = new javax.swing.JTextField();
        btnIngresarProcesamiento = new javax.swing.JButton();
        txtLog = new javax.swing.JLabel();
        txtNoSolicitud = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(1029, 520));

        btnRutaYAbrir.setText("Escoger un Archivo y Abrir");
        btnRutaYAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaYAbrirActionPerformed(evt);
            }
        });

        btnEscogerPath.setText("Escoger Ruta Reportes");
        btnEscogerPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerPathActionPerformed(evt);
            }
        });

        txtProcesamiento.setText("Indique la velocidad de procesamiento (en milisegundos):");

        valorProcesamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorProcesamientoActionPerformed(evt);
            }
        });

        btnIngresarProcesamiento.setText("Definir Tiempo");
        btnIngresarProcesamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProcesamientoActionPerformed(evt);
            }
        });

        txtLog.setText(" ");

        txtNoSolicitud.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(txtLog, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(txtProcesamiento)
                        .addGap(50, 50, 50)
                        .addComponent(valorProcesamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnIngresarProcesamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnRutaYAbrir)
                        .addGap(289, 289, 289)
                        .addComponent(btnEscogerPath))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(txtNoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEscogerPath)
                    .addComponent(btnRutaYAbrir))
                .addGap(93, 93, 93)
                .addComponent(txtLog)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcesamiento)
                    .addComponent(valorProcesamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarProcesamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(txtNoSolicitud)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    JFileChooser f = new JFileChooser();
    private void btnRutaYAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaYAbrirActionPerformed
        // TODO add your handling code here:
        //JFileChooser f = new JFileChooser();
        //System.out.println(f.showOpenDialog(null));
        
        gestorArchivosBE.abrirArchivo();
        
        /*
        
        f.showOpenDialog(null);
       //Abajo imprime solo el path, voy a usar este para que escoja el archivo con cierto nombre
        File h = new File("" + f.getCurrentDirectory() + "");
        gestorArchivosBE.setPathEntrada(f.getCurrentDirectory().toString());
        System.out.println(f.getCurrentDirectory());
        gestorArchivosBE.setFileEntrada(h);
        gestorArchivosBE.setPathDefinidoEntrada(true);
        //gestorArchivosBE.setPath(f.getCurrentDirectory());
        //Lo de abajo imprime el path junto con el archivo
        //System.out.println(f.getSelectedFile());

*/
    }//GEN-LAST:event_btnRutaYAbrirActionPerformed

    private void btnEscogerPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerPathActionPerformed
        // TODO add your handling code here:
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
        f.showOpenDialog(null);

        //
        //File h = new File("" + f.getCurrentDirectory() + "");
        File h = new File("" + f.getSelectedFile() + "");
        
        gestorArchivosBE.setFileSalida(h);
        gestorArchivosBE.setPathDefinidoSalida(true);
        
        // gestorArchivosBE.setPathSalida(f.getCurrentDirectory());
            
            //System.out.println(f.getSelectedFile());
    }//GEN-LAST:event_btnEscogerPathActionPerformed

    private void valorProcesamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorProcesamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorProcesamientoActionPerformed

    private void btnIngresarProcesamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProcesamientoActionPerformed
        // TODO add your handling code here:
        
        if (!valorProcesamiento.getText().isEmpty()) {
            System.out.println("Tiempo de procesamiento: " + valorProcesamiento.getText());
        } else {
            txtLog.setText("No hay ningún valor de procesamiento ingresado, ingrese un valor de válido!");
        }
        
        
    }//GEN-LAST:event_btnIngresarProcesamientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscogerPath;
    private javax.swing.JButton btnIngresarProcesamiento;
    private javax.swing.JButton btnRutaYAbrir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtLog;
    private javax.swing.JLabel txtNoSolicitud;
    private javax.swing.JLabel txtProcesamiento;
    private javax.swing.JTextField valorProcesamiento;
    // End of variables declaration//GEN-END:variables
}
