/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GestorArchivo;

import GestorArchivo.GestorArchivoBE;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class GestorArchivoFE extends javax.swing.JPanel {
    private GestorArchivoBE gestorArchivosBE;

    public GestorArchivoFE(GestorArchivoBE gestorArchivoBE) {
        this.gestorArchivosBE = gestorArchivoBE;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAbrirArchivo = new javax.swing.JButton();
        btnEscogerPath = new javax.swing.JButton();
        txtProcesamiento = new javax.swing.JLabel();
        valorProcesamiento = new javax.swing.JTextField();
        btnIngresarProcesamiento = new javax.swing.JButton();
        txtLog = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(1029, 520));

        btnAbrirArchivo.setText("Abrir un Archivo");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });

        btnEscogerPath.setText("Escoger Ruta Reportes");
        btnEscogerPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerPathActionPerformed(evt);
            }
        });

        txtProcesamiento.setText("Indique la velocidad de procesamiento (en milisegundos):");

        valorProcesamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorProcesamientoActionPerformed(evt);
            }
        });

        btnIngresarProcesamiento.setText("Ingresar valor");
        btnIngresarProcesamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProcesamientoActionPerformed(evt);
            }
        });

        txtLog.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtProcesamiento)
                        .addGap(50, 50, 50)
                        .addComponent(valorProcesamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLog, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIngresarProcesamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addComponent(btnAbrirArchivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(btnEscogerPath)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(txtLog))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnAbrirArchivo)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProcesamiento)
                            .addComponent(valorProcesamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIngresarProcesamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addComponent(btnEscogerPath)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    JFileChooser f = new JFileChooser();
    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed
        // TODO add your handling code here:
        //JFileChooser f = new JFileChooser();
        System.out.println(f.showOpenDialog(null));
        System.out.println(f.getCurrentDirectory());
        System.out.println(f.getSelectedFile());
    }//GEN-LAST:event_btnAbrirArchivoActionPerformed

    private void btnEscogerPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerPathActionPerformed
        // TODO add your handling code here:
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
        f.showOpenDialog(null);

        //
        //File h = new File("" + f.getCurrentDirectory() + "");
        File h = new File("" + f.getSelectedFile() + "");
        
        gestorArchivosBE.setFile(h);
        gestorArchivosBE.setPathDefinido(true);
        // gestorArchivosBE.setPathSalida(f.getCurrentDirectory());
            
            //System.out.println(f.getSelectedFile());
    }//GEN-LAST:event_btnEscogerPathActionPerformed

    private void valorProcesamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorProcesamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorProcesamientoActionPerformed

    private void btnIngresarProcesamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProcesamientoActionPerformed
        // TODO add your handling code here:
        if (!valorProcesamiento.getText().isEmpty()) {
            System.out.println("Tiempo de procesamiento: " + valorProcesamiento.getText());
        } else {
            txtLog.setText("No hay ningún valor de procesamiento ingresado, ingrese un valor de válido!");
        }
        
    }//GEN-LAST:event_btnIngresarProcesamientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnEscogerPath;
    private javax.swing.JButton btnIngresarProcesamiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtLog;
    private javax.swing.JLabel txtProcesamiento;
    private javax.swing.JTextField valorProcesamiento;
    // End of variables declaration//GEN-END:variables
}
