/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

/**
 *
 * @author debian
 */
public class GestorTarjeta extends javax.swing.JPanel {

    /**
     * Creates new form PruebaELIMINAR
     */
    public GestorTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSolicitarTarjeta = new javax.swing.JButton();
        btnRegistrarMovimiento = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnAutorizarTarjeta = new javax.swing.JButton();
        btnCancelarTarjeta = new javax.swing.JButton();
        contenidoGestorTarjeta = new javax.swing.JPanel();

        btnSolicitarTarjeta.setText("Solicitar Tarjeta");

        btnRegistrarMovimiento.setText("Registrar Movimiento");

        btnConsultar.setText("Consultar");

        btnAutorizarTarjeta.setText("Autorizar Tarjeta");

        btnCancelarTarjeta.setText("Cancelar Tarjeta");
        btnCancelarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidoGestorTarjetaLayout = new javax.swing.GroupLayout(contenidoGestorTarjeta);
        contenidoGestorTarjeta.setLayout(contenidoGestorTarjetaLayout);
        contenidoGestorTarjetaLayout.setHorizontalGroup(
            contenidoGestorTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        contenidoGestorTarjetaLayout.setVerticalGroup(
            contenidoGestorTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnSolicitarTarjeta)
                        .addGap(62, 62, 62)
                        .addComponent(btnRegistrarMovimiento)
                        .addGap(58, 58, 58)
                        .addComponent(btnConsultar)
                        .addGap(54, 54, 54)
                        .addComponent(btnAutorizarTarjeta)
                        .addGap(57, 57, 57)
                        .addComponent(btnCancelarTarjeta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(contenidoGestorTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSolicitarTarjeta)
                    .addComponent(btnRegistrarMovimiento)
                    .addComponent(btnConsultar)
                    .addComponent(btnAutorizarTarjeta)
                    .addComponent(btnCancelarTarjeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(contenidoGestorTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarTarjetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizarTarjeta;
    private javax.swing.JButton btnCancelarTarjeta;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnRegistrarMovimiento;
    private javax.swing.JButton btnSolicitarTarjeta;
    private javax.swing.JPanel contenidoGestorTarjeta;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
