/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import ReportesFE.ReportesFE;
import GestorArchivo.GestorArchivoFE;
import GestorArchivo.GestorArchivoBE;
import GestorTarjetasFE.GestorTarjetaFE;
import SQL.SQL;
import java.awt.BorderLayout;
import javax.swing.JPanel;

public class Pantalla extends javax.swing.JFrame {

    private SQL sql;
    private final GestorArchivoBE gestorArchivosBE;
    
    public Pantalla(SQL sql) {
        this.sql = sql;
        this.gestorArchivosBE = new GestorArchivoBE(sql);
        
        initComponents();
        GestorArchivoFE gestorArchivosFE = new GestorArchivoFE(gestorArchivosBE);
        showPanel(gestorArchivosFE);
    }
    
    public void showPanel(JPanel p) {
        p.setSize(1029, 520);
        p.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contenido = new javax.swing.JPanel();
        btnGestorArchivos = new javax.swing.JButton();
        btnGestorTarjeta = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        btnGestorArchivos.setText("Gestor Archivos");
        btnGestorArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestorArchivosActionPerformed(evt);
            }
        });

        btnGestorTarjeta.setText("Gestor Tarjeta");
        btnGestorTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestorTarjetaActionPerformed(evt);
            }
        });

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnGestorArchivos)
                .addGap(176, 176, 176)
                .addComponent(btnGestorTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(btnReportes)
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestorArchivos)
                    .addComponent(btnGestorTarjeta)
                    .addComponent(btnReportes))
                .addGap(35, 35, 35)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestorArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestorArchivosActionPerformed
        // TODO add your handling code here:
        GestorArchivoFE gestorArchivosFE = new GestorArchivoFE(gestorArchivosBE);
        showPanel(gestorArchivosFE);
    }//GEN-LAST:event_btnGestorArchivosActionPerformed

    private void btnGestorTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestorTarjetaActionPerformed
        // TODO add your handling code here:
        GestorTarjetaFE gestorTarjetaFE = new GestorTarjetaFE(sql, gestorArchivosBE);
        showPanel(gestorTarjetaFE);
    }//GEN-LAST:event_btnGestorTarjetaActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        ReportesFE reportesFE = new ReportesFE(sql, gestorArchivosBE);
        showPanel(reportesFE);
    }//GEN-LAST:event_btnReportesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestorArchivos;
    private javax.swing.JButton btnGestorTarjeta;
    private javax.swing.JButton btnReportes;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
