/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

/**
 *
 * @author debian
 */
public class ReportesFE extends javax.swing.JPanel {

    /**
     * Creates new form Reportes
     */
    public ReportesFE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEstadoCuenta = new javax.swing.JButton();
        btnListadoTarjetas = new javax.swing.JButton();
        btnListadoSolicitudes = new javax.swing.JButton();
        contenidoReportes = new javax.swing.JPanel();

        btnEstadoCuenta.setText("Ver Estado de Cuenta");

        btnListadoTarjetas.setText("Listado de Tarjetas");
        btnListadoTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoTarjetasActionPerformed(evt);
            }
        });

        btnListadoSolicitudes.setText("Listado de Solicitudes");
        btnListadoSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoSolicitudesActionPerformed(evt);
            }
        });

        contenidoReportes.setPreferredSize(new java.awt.Dimension(980, 440));

        javax.swing.GroupLayout contenidoReportesLayout = new javax.swing.GroupLayout(contenidoReportes);
        contenidoReportes.setLayout(contenidoReportesLayout);
        contenidoReportesLayout.setHorizontalGroup(
            contenidoReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        contenidoReportesLayout.setVerticalGroup(
            contenidoReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnEstadoCuenta)
                .addGap(240, 240, 240)
                .addComponent(btnListadoTarjetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListadoSolicitudes)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(contenidoReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstadoCuenta)
                    .addComponent(btnListadoTarjetas)
                    .addComponent(btnListadoSolicitudes))
                .addGap(18, 18, 18)
                .addComponent(contenidoReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListadoSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoSolicitudesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListadoSolicitudesActionPerformed

    private void btnListadoTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoTarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListadoTarjetasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadoCuenta;
    private javax.swing.JButton btnListadoSolicitudes;
    private javax.swing.JButton btnListadoTarjetas;
    private javax.swing.JPanel contenidoReportes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
